In [1]:
# Setting up dependencies to be utilized later here.
import pandas as pd
from pathlib import Path

import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np


#We can add more dependencies... or we can remove dependencies we haven't
#utilized when we finish the project.

In [2]:
# Converting .csv file into a dataframe for data manipulation
wa_lottery_path = Path("Resources/2021_lottery_data.csv")
wa_lottery_pd = pd.read_csv(wa_lottery_path)

# displaying .csv just to see what data we have
wa_lottery_pd

           date weekday winning_numbers  powerball  powerplay       jackpot
0      5/7/2014     Wed  17-29-31-48-49         34          2  7.000000e+07
1     5/10/2014     Sat   4-31-41-47-55          1          2  9.000000e+07
2     5/14/2014     Wed   7-33-39-52-55         33          3  9.000000e+07
3     5/17/2014     Sat  23-32-39-47-49         22          3  1.140000e+08
4     5/21/2014     Wed   4-20-34-39-58         31          5  1.140000e+08
..          ...     ...             ...        ...        ...           ...
945  10/24/2022     Mon  18-23-35-45-54         16          4  6.250000e+08
946  10/26/2022     Wed  19-36-37-46-56         24          2  7.000000e+08
947  10/29/2022     Sat  19-31-40-46-57         23          3  8.250000e+08
948  10/31/2022     Mon  13-19-36-39-59         13          3  1.000000e+09
949   11/2/2022     Wed   2-11-22-35-60         23          2  1.200000e+11

[950 rows x 6 columns]

In [11]:
print(wa_lottery_pd.describe())

# pie chart
print(wa_lottery_pd['weekday'].value_counts())

        powerball   powerplay       jackpot
count  950.000000  950.000000  9.500000e+02
mean    14.510526    2.694737  2.923004e+08
std      8.165142    1.142840  3.890469e+09
min      1.000000    0.000000  2.000000e+07
25%      8.000000    2.000000  7.000000e+07
50%     14.500000    2.000000  1.255000e+08
75%     21.000000    3.000000  2.215000e+08
max     35.000000   10.000000  1.200000e+11
Wed    444
Sat    443
Mon     63
Name: weekday, dtype: int64

KeyError: False